#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jets3t
Version  : 0.9.0
Release  : 1
URL      : http://bitbucket.org/jmurty/jets3t/downloads/jets3t-0.9.0.zip
Source0  : http://bitbucket.org/jmurty/jets3t/downloads/jets3t-0.9.0.zip
Source1  : https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.jar
Source2  : https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: mvn-jets3t-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
JetS3t
======
JetS3t is a free, open-source Java toolkit and application suite for
Amazon Simple Storage Service (Amazon S3), Amazon CloudFront content
delivery network, and Google Storage for Developers.

%package data
Summary: data components for the mvn-jets3t package.
Group: Data

%description data
data components for the mvn-jets3t package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.jar
/usr/share/java/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.pom
